### ISSUE TITLE
EVA resets home timer

### ISSUE THREAD

**Issue by bounty123** [BobPalmer/USI-LS#211]
Hi! Going on EVA resets also the home timer, so habitation can be sustained indefinitely with a single vessel. Easy to reproduce with any vessel, but I attached a clean USI quicksave. Reproduce test: time-warp to a lower home value, do an EVA with a kerbal. Enter the vessel again, home timer is reset to the default value. Repeat any more time (until supplies run out :).
Bug appeared in release .17, home timer still workes fine in .16.
[save.zip](https://github.com/BobPalmer/USI-LS/files/722128/save.zip)

**Comment by chronotopian** [comment]
I've had this happen too. +1

**Comment by BobPalmer** [comment]
Fixed in the next release

**Comment by Gnurfos** [comment]
@BobPalmer if you have something on your side that's fine, but I don't think this one is solved by my recent changes (I'm still experiencing it, plus strange things where MaxOffKerbinTime gets reset to now+30d. I suspect both could be related to kerbal tracking/fetching mishaps, and will investigate more).

**Comment by Gnurfos** [comment]
The KerbalIsMissing() check has disappeared [here](https://github.com/BobPalmer/USI-LS/commit/7a9ca08150b2f4798348a8d66333db77eb467a4f#diff-5de4cb339b081ab5fcc8f0d67083090bL406).
Now when a Kerbal goes on EVA, it appears "dead" to its original vessel's CheckForDeadKerbals(), which has it untracked. It is soon fetched and created afresh with MaxOffKerbinTime=now+30d and LastAtHome=now.

**Comment by BobPalmer** [comment]
Yep, just have not checked it in yet.
