### ISSUE TITLE
Some Life Support Recyclers are not working.

### ISSUE THREAD

**Issue by fat-lobyte** [BobPalmer/USI-LS#76]
Hi! It seems that although some Life Support Recyclers work, some of them simply don't.

http://imgur.com/a/kpNfX

Here's what works:

- Mobile Processing Lab
- UKS Pioneer Module (Orbital)
- UKS Kerbitat (tm) (Orbital)
- MK-V 'Scout' Command Pod
- UKS Pioneer Module (Surface)
- UKS Kerbitat (tm) (Surface)
- MK-V Habitation Module, albeit the recycling rate is very low.

Here's what doesn't work:
- UKS Aeroponics Module (Orbital)
- OKS Agricultural Module
- OKS Habitation Ring
- UKS Aeroponics Module (Surface)

**Comment by fat-lobyte** [comment]
Update: all parts where the recycler doesn't work have MKSModule. None of the parts where the recyclers do work have it.

**Comment by fat-lobyte** [comment]
I think I might have found an issue which could cause this bug.

Look at this [ModuleLifeSupportRecycler.PostProcess](https://github.com/BobPalmer/USI-LS/blob/master/Source/USILifeSupport/ModuleLifeSupportRecycler.cs#L18), 
    
    RecyclerIsActive = Math.Abs(result.TimeFactor - deltaTime) < ResourceUtilities.FLOAT_TOLERANCE;

All parts with `ModuleLifeSupportRecycler` *without* `MKSModule` are processed every single frame, and `result.TimeFactor` is always exactly equal to `deltaTime`, and on my system it's 0.02.

All parts with `ModuleLifeSupportRecycler` that *do* have `MKSModule` apparently only refresh every 5 seconds. In this situation, `result.TimeFactor` is suddenly a lot higher (0.18) the `deltaTime` stays the same (0.02). This leads to the comparison to always be false, and to the converters being effectively disabled.
Note that 

I'm not really sure what the code in PostProcess is supposed to do, so I don't know how to "fix" it properly. However, replacing the whole line with

    RecyclerIsActive = true;

Seems to work just fine, and fixes the issue.

**Comment by apocriva** [comment]
I've recorded my observations on this issue.

[Album of results](http://imgur.com/a/cHS9Z).

Now that I'm looking back at it though, mulch production is almost assuredly not related, given that mulch production isn't actually tied to having started the recyclers. :)

**Comment by fat-lobyte** [comment]
@apocriva Yes, mulch doesn't have to do anything with it.
Also note that the ReplacementPart consumption is a different issue, namely #78, and it's fixed in PR #82 .

**Comment by TheGroovyMule** [comment]
Curious, has this been implemented in a fix yet? I'm still not getting a response from the parts listed above.

**Comment by fat-lobyte** [comment]
Same for me.

**Comment by TheGroovyMule** [comment]
Is there anyway the current fix in this thread can be compiled into a working version? I looked into doing it myself but I don't have Visual Studio.

**Comment by BobPalmer** [comment]
It's not a fix tho.  That code is there for a very good reason.

**Comment by gandi3k** [comment]
cant get the following modules to do their work either:

    UKS Aeroponics Module (Orbital)
    OKS Agricultural Module
    OKS Habitation Ring
    UKS Aeroponics Module (Surface)

**Comment by gandi3k** [comment]
a minor addendum:

if i do the following in the OKS_HabRing.cfg the Hab ring does it 25% recyle

	//MODULE
	//{
	//	name = MKSModule
	//	workSpace = 0
	//	livingSpace = 10
	//	hasGenerators = false
	//}

**Comment by kjnicoletti** [comment]
As of 1.1 this is still an issue

Works:

* Pioneer - orbital and surface
* Mobile Processing Lab
* Kerbitat (water purifier) - orbital and surface
* MK-V Habitation Module

Doesn't work:

* MK-V Scout Command Pod
* Aeroponics Module - orbital and surface
* OKS Agricultural Module
* OKS Habitation Module
* MK-V Agricultural Module

KSP (1.1.0.1230) running 64bit on Windows with with just USI-LS (0.4.2), UKS (0.40.1.1) and ModuleManager (2.6.23).

**Comment by MarkSRobinson** [comment]
I tried with USI-LS 0.4.3.1 and UKS 0.40.3.0 and the Scout and Habitation modules work.  Although the scout module requires crew to function

**Comment by TheGroovyMule** [comment]
All the parts appear to be functioning, but are they supposed to stack in any way? I ask as rather then stacking, it appears that the mod uses the highest efficiency part on the craft (Usually the Pioneer module) for life support. 
I made a stack of the OKS Agricultural Module, OKS Habitation Ring, UKS Pioneer Module, and the UKS Aeroponics Module. With 4500 supplies and 3 Kerbals consuming 29.2 supplies per day without any life support modules runnning, the farthest I can get it down is 7.3 per day, which is while the Pioneer module is running, regardless of what other modules are at work.

**Comment by fat-lobyte** [comment]
They are supposed to Stack in the sense that the capacityof the converers is extended. The first 5 (or whatever the capacity of the Converter is) kerbals get the reduction of the best Converter, the next  ones that of the second best, and so on. Your rate is working as intended.
